language: rust
rust:
  - 1.18.0
  - nightly
before_install:
  - sudo apt-get update
addons:
  postgresql: "9.4"
  apt:
    packages:
      - libcurl4-openssl-dev
      - libelf-dev
      - libdw-dev
      - cmake
      - gcc
      - binutils-dev
matrix:
  allow_failures:
    - rust: nightly
services:
  - postgresql
before_script:
  - rvm install ruby-2.3.3 --binary --fuzzy
  - rvm use 2.3.3
  - gem install bundler
  - bundle install
  - nvm install 7.4.0
  - npm install -g yarn@1.0.1
  - yarn install
  - rake db:create
  - rake db:migrate
script:
  - cargo build --verbose
  - RUST_BACKTRACE=1 cargo test --verbose -- --nocapture
  - npm run lint
  - npm test
env:
  global:
  - USER_AGENT=Mozilla/5.0 (iPhone; CPU iPhone OS 9_1 like Mac OS X) AppleWebKit/601.1.46 (KHTML, like Gecko) Version/9.0 Mobile/13B143 Safari/601.1
  - secure: S1scCqP3oLWhF2/t2FBxmyluE0PUKMyNvMhKz+NfDstwV3kqdD2MCa0XTP/zW6bB7rd1BOeKM7Ofa8brFafkMM2Gt0/r1upG0m1Rf3nKdsIliJSY4uc4RMc/8k75dFlqT94Tah8t6fAIukwy/DlYo98pauJAqq0YHb2dzBAvq+0=
  - secure: V3xd6SmedlaFZaypwx2Cn/nr37I+pCXMOtOKkrtYA59Ci/H4lgMZg1sDMLsLmb+r71ZpYOwm9NrfYeIgng+PHfKEaAnf0I0t4g6VbDtnTpmGKc+qav4bDl/FYTbGbfeqPE9PoAZDYzRKDG1bbB5y2oWJmuTdIU6CTsoAjF6NONI=
  - secure: DeNLhCa1B9Y3/CcVNQQ89ydUAWprqQS349PiiEsqjcV+p7a/u8mkeFsn9yqVqq3HC6na8lQgIEbjzOCfPXlGpldasZZf0j/5yrlyx2ERMhmWIce1o0w68hYQzI1bSTDbBdJsNNAUgtWoQ3U6nFnlRf+73PWDtkL7s5LiF7znK98=
