language: rust
rust:
  - 1.14.0
  - nightly
matrix:
  allow_failures:
    - rust: nightly
script:
  - cargo build --verbose
  - cargo test --verbose
  - nvm install 7.2.0
  - npm install -g yarn
  - yarn install
  - npm run lint
  - npm test
