language: rust
rust:
  - 1.26.2
  - nightly
before_install:
  - sudo apt-get update
addons:
  postgresql: "9.6"
  apt:
    packages:
      - libcurl4-openssl-dev
      - libelf-dev
      - libdw-dev
      - cmake
      - gcc
      - binutils-dev
matrix:
  allow_failures:
    - rust: nightly
services:
  - postgresql
before_script:
  - rvm install ruby-2.6.5 --binary --fuzzy
  - rvm use 2.6.5
  - gem install bundler
  - bundle install
  - nvm install 7.4.0
  - npm install -g yarn@1.0.1
  - yarn install
  - rake db:create
  - rake db:migrate
script:
  - cargo build --verbose
  - RUST_BACKTRACE=1 cargo test --verbose -- --nocapture --test-threads=1
  - npm run lint
  - npm test
env:
  global:
  - USER_AGENT=Mozilla/5.0 (iPhone; CPU iPhone OS 9_1 like Mac OS X) AppleWebKit/601.1.46 (KHTML, like Gecko) Version/9.0 Mobile/13B143 Safari/601.1
