language: rust
rust:
  - 1.14.0
  - nightly
matrix:
  allow_failures:
    - rust: nightly
script:
  - cargo build --verbose
  - RUST_BACKTRACE=1 cargo test --verbose -- --nocapture
  - nvm install 7.4.0
  - npm install -g yarn
  - yarn install
  - npm run lint
  - npm test
