[package]

name = "pink_spider"
version = "0.0.1"
authors = ["kumabook@live.jp"]

#![feature(os)]

[[bin]]
name = "app"
[[bin]]
name = "drop_tables"
path = "src/bin/drop_tables.rs"

[dependencies]
iron         = "*"
router       = "*"
postgres     = "*"
regex_macros = "*"
hyper        = "*"
regex        = "*"
urlencoded   = "*"
tendril      = "*"
[dependencies.string_cache]
git = "https://github.com/servo/string-cache"
[dependencies.string_cache_plugin]
git = "https://github.com/servo/string-cache"
[dependencies.html5ever]
git = "https://github.com/servo/html5ever"
[dependencies.html5ever_dom_sink]
git = "https://github.com/servo/html5ever"
