[package]

name = "pink_spider"
version = "0.0.1"
authors = ["kumabook@live.jp"]

#![feature(os)]

[[bin]]
name = "app"
[[bin]]
name = "drop_tables"
path = "src/bin/drop_tables.rs"

[dependencies]
iron            = "*"
router          = "*"
postgres        = "*"
hyper           = "*"
regex           = "*"
string_cache    = "*"
urlencoded      = "*"
rustc-serialize = "*"
tendril         = "*"
html5ever       = "*"
url             = "*"
lazy_static     = "*"
