[package]

name = "pink_spider"
version = "1.0.0"
authors = ["kumabook@live.jp"]

#![feature(os)]

[[bin]]
name = "app"

[[bin]]
name = "update_tracks"
path = "src/update_tracks.rs"

[[bin]]
name = "update_playlists"
path = "src/update_playlists.rs"

[features]
default = ["postgres"]

[dependencies]
iron             = "*"
router           = "*"
hyper            = "*"
hyper-native-tls = "^0"
regex            = "*"
string_cache     = "*"
urlencoded       = "*"
tendril          = "*"
html5ever        = "*"
scraper          = "*"
url              = "*"
lazy_static      = "*"
toml             = "0.2.1"
uuid             = { version = "0.5.0", features = ["v4", "serde"] }
staticfile       = "*"
chrono           = { version = "*", features = ["serde"] }
queryst          = "*"
bodyparser       = "*"
serde            = "^1"
serde_json       = "^1"
serde_derive     = "^1"
[dependencies.mount]
git = "https://github.com/iron/mount.git"
[dependencies.postgres]
git = "https://github.com/sfackler/rust-postgres.git"
branch = "master"
features = ["with-uuid", "with-chrono"]
optional = true
