[package]

name = "pink_spider"
version = "0.0.1"
authors = ["kumabook@live.jp"]

#![feature(os)]

[[bin]]
name = "app"
[[bin]]
name = "drop_tables"
path = "src/bin/drop_tables.rs"

[dependencies.urlencoded]
git = "https://github.com/kumabook/urlencoded.git"
rev = "128a59a4c6f02d6d14408cf086d475c8ead2b303"
[dependencies.string_cache]
git = "https://github.com/kumabook/string-cache"
[dependencies.string_cache_plugin]
git = "https://github.com/kumabook/string-cache"

[dependencies]
iron         = "*"
router       = "*"
postgres     = "*"
regex_macros = "*"
hyper        = "*"
[dependencies.regex]
git = "https://github.com/rust-lang/regex.git"
rev = "910aef40aca4f525dd2fecc54a78e9bc183039d1"
[dependencies.html5ever]
git = "https://github.com/kumabook/html5ever"
rev = "95d7e2b965659720a6c439551883188014167bff"
