[package]

name = "pink_spider"
version = "0.1.0"
authors = ["kumabook@live.jp"]

#![feature(os)]

[[bin]]
name = "app"

[[bin]]
name = "update_tracks"
path = "src/update_tracks.rs"

[features]
default = ["postgres"]

[dependencies]
iron            = "*"
router          = "*"
hyper           = "*"
regex           = "*"
string_cache    = "*"
urlencoded      = "*"
rustc-serialize = "*"
tendril         = "*"
html5ever       = "*"
scraper         = "*"
url             = "*"
lazy_static     = "*"
toml            = "0.2.1"
uuid            = { version = "*", features = ["v4", "rustc-serialize", "serde"] }
staticfile      = "*"
chrono          = { version = "*", features = ["serde", "rustc-serialize"] }
queryst         = "*"
bodyparser      = "*"
serde_json      = "*"
[dependencies.mount]
git = "https://github.com/iron/mount.git"
[dependencies.postgres]
version = "0.12"
features = ["with-uuid", "with-chrono"]
optional = true
