[package]

name = "pink_spider"
version = "0.0.1"
authors = ["kumabook@live.jp"]

#![feature(os)]

[[bin]]
name = "app"

[features]
default = ["postgres"]

[dependencies]
iron            = "*"
router          = "*"
hyper           = "*"
regex           = "*"
string_cache    = "*"
urlencoded      = "*"
rustc-serialize = "*"
tendril         = "*"
html5ever       = "*"
url             = "*"
lazy_static     = "*"
uuid            = "*"

[dependencies.postgres]
version = "*"
features = ["uuid"]
optional = true
