[package]

name = "pink_spider"
version = "0.0.1"
authors = ["kumabook@live.jp"]

#![feature(os)]

[[bin]]
name = "app"

[dependencies]
iron = "*"
postgres = "0.7"
regex = "0.1.8"
regex_macros = "0.1.8"

[dependencies.string_cache]
git = "https://github.com/servo/string-cache"
[dependencies.string_cache_plugin]
git = "https://github.com/servo/string-cache"
[dependencies.html5ever]
git = "https://github.com/servo/html5ever"

