version: '2'
volumes:
  postgres:
    driver: 'local'
services:
  web:
    build: .
    env_file:
      - .env
    depends_on:
      - db
    ports:
      - "8080:8080"
    volumes:
      - ./src:/app/src
      - ./web:/app/web
      - ./lib:/app/lib
      - ./Cargo.toml:/app/Cargo.toml
      - ./Cargo.lock:/app/Cargo.lock
      - ./Rakefile:/app/Rakefile
      - ./package.json:/app/package.json
      - ./yarn.lock:/app/yarn.lock
      - ./webpack.config.js:/app/webpack.config.js
  db:
    image: postgres
    volumes:
      - postgres:/var/lib/postgres
