default: &default
  adapter: postgresql
  encoding: unicode
  pool: 5

development:
  <<: *default
  database: pink_spider_development_<%=
    `git symbolic-ref --short HEAD`
  %>
test:
  <<: *default
  database: pink_spider_test

production:
  <<: *default
  database: pink_spider_production
  username: pink_spider
  password: <%= ENV['PINK_SPIDER_DATABASE_PASSWORD'] %>

