default: &default
  adapter: postgresql
  encoding: unicode
  pool: 5

development:
  <<: *default
  database: pink_spider_development
  username: pink_spider
  password: pink_spider
test:
  <<: *default
  database: pink_spider_test
  username: pink_spider
  password: pink_spider

production:
  <<: *default
  database: pink_spider_production
  username: pink_spider
  password: <%= ENV['PINK_SPIDER_DATABASE_PASSWORD'] %>

