default: &default
  adapter: postgresql
  encoding: unicode
  pool: 5

development:
  <<: *default
  database: pink_spider_development
  username: postgres
  password: postgres
test:
  <<: *default
  database: pink_spider_test
  username: postgres
  password: postgres

production:
  <<: *default
  database: pink_spider_production
  username: postgres
  password: <%= ENV['PINK_SPIDER_DATABASE_PASSWORD'] %>

